#include "arduino_secrets.h"
#include <DS18B20.h>
#include <UniversalTelegramBot.h>
#include <WiFiClientSecure.h>
#include <ArduinoJson.h>
/* 
  Sketch generated by the Arduino IoT Cloud Thing "MoCaFri"
  https://create.arduino.cc/cloud/things/a1b93dfd-4119-4d88-abb0-6b956eb5893d 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  CloudTemperatureSensor temperatura;
  bool portaAberta;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"

#define RSW 4
#define LED 8
#define TMP 2


WiFiClientSecure secured_client;
UniversalTelegramBot bot(BOT_TOKEN, secured_client);

DS18B20 ds(TMP);

void setup() {
  pinMode(RSW, INPUT);
  pinMode(LED, OUTPUT);
  // Initialize serial and wait for port to open:
  Serial.begin(9600);

  
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();
  
  secured_client.setCACert(TELEGRAM_CERTIFICATE_ROOT);  
  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();

}
unsigned long TempoPortaAbertaSec = 0;
unsigned long TempoPortaAbertaRef = 0;
bool AlarmePortaEmEspera = true;
bool AlarmeTemperaturaEmEspera = true;

bool estadoLed = false;

void loop() {
  ArduinoCloud.update();
  
  portaAberta = !digitalRead(RSW);
    
  if(portaAberta){
    TempoPortaAbertaSec += 1; // Incrementar contador de segundos de porta aberta
  }
  else{
    TempoPortaAbertaSec = 0;
    if(!AlarmePortaEmEspera){
      AlarmePortaEmEspera = true; //Permite que o alarme de tempo de porta seja enviado novamente
      bot.sendMessage(CHAT_ID, "Porta normalizada.", "");
    }
    
  }

  //Verifica tempo de porta aberta e ativa alarme
  if(AlarmePortaEmEspera && TempoPortaAbertaSec >= MAX_DOOR_TIME_SEC){
    bot.sendMessage(CHAT_ID, "Porta aberta por tempo limite!", ""); //Envia alarme para telegram
    AlarmePortaEmEspera = false; // Desativa alarme porta até ela ser fechada novamente
  }
  
  //Aquisic. Temperatura
  while (ds.selectNext()) {
    temperatura = ds.getTempC();
  }
  
  int tempInt = (int)temperatura;
  if(tempInt >= MIN_TEMPERATURE && tempInt <= MAX_TEMPERATURE){
    if(!AlarmeTemperaturaEmEspera){
      AlarmeTemperaturaEmEspera = true; //Permite que o alarme de temperatura seja enviado novamente
      bot.sendMessage(CHAT_ID, "Temperatura normalizada.", "");
    }
  }
  //Ativa alarme temperatura
  else if(AlarmeTemperaturaEmEspera){
    if(tempInt < MIN_TEMPERATURE){
      bot.sendMessage(CHAT_ID, "Temperatura baixa!", ""); //Envia alarme para telegram
    }
    else{
      bot.sendMessage(CHAT_ID, "Temperatura alta!", ""); //Envia alarme para telegram
    }
    AlarmeTemperaturaEmEspera = false; // Desativa alarme temperatura até ela ser fechada novamente
  }
  estadoLed = !estadoLed;
  digitalWrite(LED,estadoLed);
  delay(1000);
}



void onPortaAbertaChange()  {
  // Add your code here to act upon PortaAberta change
  
}

void onTemperaturaChange()  {
  // Add your code here to act upon Temperatura change
}