// Code generated by Arduino IoT Cloud, DO NOT EDIT.
// → Acrescentei guarda de inclusão e callbacks

#ifndef _THING_PROPERTIES_h
#define _THING_PROPERTIES_h

#include <WiFi.h>
#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[] = "03e7132b-8c2f-4db0-8b50-ff88c7da283b";
const char SSID[]  = "azeitona";
const char PASS[]  = "ruimdemais";
const char DEVICE_KEY[] = "yXFZnTDEPrbTeP@JhOqmv@jyG";

float temperature;
bool  doorState;

/* Protótipos dos callbacks declarados no sketch ----------------- */
void onTemperatureChange();
void onDoorStateChange();

/* Registro das propriedades + credenciais ----------------------- */
void initProperties() {

  /*  Atenção à versão da lib:                                   *
   *  se estiver usando >=2.4.0 troque para setDeviceId / setDeviceKey */
  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);

  ArduinoCloud.addProperty(temperature, READWRITE, ON_CHANGE, onTemperatureChange);
  ArduinoCloud.addProperty(doorState,   READWRITE, ON_CHANGE, onDoorStateChange);
}

/* Handler Wi-Fi usado internamente */
WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);

#endif  // _THING_PROPERTIES_h
